development:
  AWS_REGION: ap-southeast-2
  S3_HOSTNAME: s3-ap-southeast-2.amazonaws.com
  ACCESS_KEY_ID: AKIAIVNB5GRUFKYIWLAA
  SECRET_ACCESS_KEY: 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

production:
  SECRET_KEY_BASE: 5395b86a5ba1eb25e4aaa26c0212f8ee3a84dd508794216e737f3a8b2ef64644bc4c126e4027042bae6f06c77794986d3a0b3f498d30f14413ecafc40af4210d
  ACCESS_KEY_ID: AKIAIVNB5GRUFKYIWLAA
  SECRET_ACCESS_KEY: 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
  AWS_REGION: ap-southeast-2